source 'http://rubygems.org'

gem 'rails', '3.1.0.rc1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Asset template engines
gem 'sass'
gem 'coffee-script'
gem 'uglifier'

gem 'jquery-rails'

# MongoDB
gem 'mongo_mapper'
gem 'bson_ext'

gem 'rake', '0.8.7'
# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development,:test do
  # Pretty printed test output
  gem 'turn', :require => false
  gem "rspec-rails", ">= 2.0.0"
  gem "cucumber-rails", ">= 0.3.2"
  gem "webrat", ">= 0.7.2"
  gem "database_cleaner"
end
